### ISSUE TITLE
Add the python code to the repos

### ISSUE THREAD

**Issue by MaximilienNaveau** [machines-in-motion/robot_estimation#1]
@ahmadgazar Can you add your python code to this repos so we can all work with the same things?

**Comment by ahmadgazar** [comment]
Just pushed the python EKF class [here](https://github.com/machines-in-motion/robot_estimation/tree/master/src/python). As I mentioned earlier in the email, I am still starting to work on it. I think we need to discuss the design choices we mentioned in the email as well, but I will open that in a different issue.
